[package]
name = "project"
version = "0.1.0"
authors = ["louisgalluzzi <louisgalluzzi@email.arizona.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "project"
path = "main.rs"
